### ISSUE TITLE
新版翻译顺序错位

### ISSUE THREAD

**Issue by KT-TY** [IAmNotGEM/Nomifactory-GTCEu-Port---zh_CN#1]
前期的任务有些错位了，包括终局那个元素周期表(比如铁错位成了锰)

**Comment by IAmNotGEM** [comment]
> 
OK，我看看。

**Comment by IAmNotGEM** [comment]
> 前期的任务有些错位了，包括终局那个元素周期表(比如铁错位成了锰)

具体哪个错位了

**Comment by IAmNotGEM** [comment]
> 前期的任务有些错位了，包括终局那个元素周期表(比如铁错位成了锰)

前期的

**Comment by IAmNotGEM** [comment]
> 

这是nomi-ceu的汉化，不是Nomifactory的。
https://github.com/xzsk2/Nomifactory-zh_CN/releases/tag/latest

**Comment by KT-TY** [comment]
我下的1.4版本nomi-ceu的包，土高炉任务在我这里显示的是镀铑钯金，开局左上角一堆复选框任务，那个床的图案是装配线自动化，书是多层纤维增强电路板，右边新月扳手是无限战争，无限水是地狱物质。终局元素周期表全部后移了一位从氦开始，钙是57号元素：镧。还有很多这样的错位。。。

**Comment by KT-TY** [comment]
已解决，需要更新版本至1.4.2即可。

**Comment by IAmNotGEM** [comment]
> 已解决，需要更新版本至1.4.2即可。

ok
