### ISSUE TITLE
大佬有空可以加个 CC BY-NC-SA 4.0 协议吗？

### ISSUE THREAD

**Issue by zero6six** [IAmNotGEM/Nomifactory-GTCEu-Port---zh_CN#10]
因为不加的话是保留所有权利的XD

**Comment by IAmNotGEM** [comment]
随便用。




阿丽塔
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "IAmNotGEM/Nomifactory-GTCEu-Port---zh_CN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月18日(星期六) 晚上11:47
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[IAmNotGEM/Nomifactory-GTCEu-Port---zh_CN] 大佬有空可以加个 CC BY-NC-SA 4.0 协议吗？ (Issue #10)





 
因为不加的话是保留所有权利的XD
