### ISSUE TITLE
nomi-ceu(1.4.3)任务书翻译错位

### ISSUE THREAD

**Issue by notnotype** [IAmNotGEM/Nomifactory-GTCEu-Port---zh_CN#7]
见 release note：https://github.com/tracer4b/nomi-ceu/pull/152

**Comment by IAmNotGEM** [comment]
https://github.com/IAmNotGEM/Nomifactory-GTCEu-Port---zh_CN/releases/tag/1.4.3 @notnotype

**Comment by notnotype** [comment]
感谢 👍🏻
