### ISSUE TITLE
大佬有空更新 1.5.1 版本的汉化么

### ISSUE THREAD

**Issue by zero6six** [IAmNotGEM/Nomifactory-GTCEu-Port---zh_CN#8]
大佬辛苦了，谢谢大佬。

**Comment by IAmNotGEM** [comment]
我累了，你们来维护叭


阿丽塔
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "IAmNotGEM/Nomifactory-GTCEu-Port---zh_CN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月5日(星期天) 中午1:57
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[IAmNotGEM/Nomifactory-GTCEu-Port---zh_CN] 大佬有空更新 1.5.1 版本的汉化么 (Issue #8)





 
大佬辛苦了，谢谢大佬。

**Comment by zero6six** [comment]
大佬能否帮我看下我的 fork，以及重构成这样是否可以。

**Comment by guanghui8866** [comment]
要玩就玩高版本
